### ISSUE TITLE
Encoding and decoding encapsulated pixel data

### ISSUE THREAD

**Issue by lamyj** [lamyj/odil#13]
Odil has currently no way of encoding/decoding/transcoding encapsulated data (e.g. JPEG, JPEG-LS or RLE). Such a feature should however not be limited to a set of fixed encoders/decoders: if a user wants to replace IJG's libjpeg by whatever shiny, high-performance, GPU-enabled library is locally available, this should be possible. The prototype in the [encapsulated-pixe-data branch](https://github.com/lamyj/odil/tree/encapsulated-pixel-data) could do the trick:
* Generic design of encoders and decoders (cf. [Encoder](https://github.com/lamyj/odil/blob/encapsulated-pixel-data/src/odil/encapsulated_pixel_data.h#L27-L39) and [Decoder](https://github.com/lamyj/odil/blob/encapsulated-pixel-data/src/odil/encapsulated_pixel_data.h#L41-L45) typedefs)
* [Run-time selection of encoders/decoders](https://github.com/lamyj/odil/blob/encapsulated-pixel-data/src/odil/encapsulated_pixel_data.h#L47-L51)
* Possibility of sane defaults (example with RLE [header](https://github.com/lamyj/odil/blob/encapsulated-pixel-data/src/odil/rle_lossless.h) and [code](https://github.com/lamyj/odil/blob/encapsulated-pixel-data/src/odil/rle_lossless.cpp))

Note that the RLE example there for example purposes only, and probably broken in more ways than you would care to count…

@cguebert, @fbridault, @JohanMoreau: you have more experience in using encapsulated pixel data than I do. What's your take on this design?

**Comment by cguebert** [comment]
I'm not sure if transcoding should be done by Odil. Firstly because adding some library to support event the most common types would triple the code size of Odil. Secondly if we want to do it ourselves, it is already possible to get the pixel data, do our stuff, and write it back.

The only thing missing from my point of view is the ability to get the original transfer syntax in which the DataSet has been encoded. I suggest adding a member directly into the class (https://github.com/cguebert/odil/commit/88dc89c78a3913e8cda5f5c912ddcadcf2450f4c)

**Comment by lamyj** [comment]
Code size and dependency handling is a perfectly valid point: I'll think about for a few more days, but this issue will probably be closed as wontfix by the end of the week.

Regarding storing the TS in the data set, I'd just like to rename `get_original_transfer_syntax` to `get_transfer_syntax`, since this member can be used to carry the *current* transfer syntax and be passed later to the `Writer`.

**Comment by lamyj** [comment]
Closing as wontfix, but keeping the branch for now.
